# Generated by Django 3.0.8 on 2020-09-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0005_auto_20200909_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='aerobic_training_effect',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='anaerobic_training_effect',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
