# Generated by Django 3.0.8 on 2020-09-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0006_auto_20200909_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='aerobic_training_effect',
        ),
        migrations.RemoveField(
            model_name='traces',
            name='anaerobic_training_effect',
        ),
        migrations.RemoveField(
            model_name='traces',
            name='calories',
        ),
    ]
