# Generated by Django 3.0.8 on 2020-09-11 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0007_auto_20200909_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='avg_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='altitude_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='avg_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='avg_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='cadence_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='coordinates_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='distance_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='heart_rate_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='max_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='max_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='max_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='min_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='min_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='min_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='min_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='min_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='speed_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='temperature_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='timestamps_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AddField(
            model_name='uicacheactivitydata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
