# Generated by Django 3.0.8 on 2020-09-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0008_auto_20200911_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='avg_altitude',
        ),
    ]
