# Generated by Django 3.0.8 on 2020-09-12 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0009_remove_traces_avg_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ui_cache_activity_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizer.UICacheActivityData'),
        ),
    ]
