# Generated by Django 3.0.8 on 2020-09-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0010_activity_ui_cache_activity_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='avg_cadence',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='avg_heart_rate',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='avg_temperature',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='max_altitude',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='max_cadence',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='max_heart_rate',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='max_temperature',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='min_altitude',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='min_cadence',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='min_heart_rate',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='min_speed',
        ),
        migrations.RemoveField(
            model_name='uicacheactivitydata',
            name='min_temperature',
        ),
    ]
