# Generated by Django 3.0.8 on 2020-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0012_auto_20200916_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='altitude_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='cadence_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='coordinates_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='distance_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='heart_rate_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='speed_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='temperature_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='uicacheactivitydata',
            name='timestamps_list',
            field=models.CharField(max_length=10000000000, null=True),
        ),
    ]
